### ISSUE TITLE
Postman: completar Postman workspace con testeos rest

### ISSUE THREAD

**Issue by ezequielcinalli** [ezequielcinalli/tpe-arquitecturas-web#10]
Agregar al [Postman workspace](https://www.postman.com/ezequielcinalli/workspace/tp3-arquitecturas-web/overview):

- [x] City
- [x] Student @Germandf 
- [x] Career @gherbiandrea 
- [x] StudentCareer @Germandf

**Comment by Germandf** [comment]
Student y StudentCareer los dejamos para el final una vez esté resuelto el tema de los Dtos

**Comment by ezequielcinalli** [comment]
@LucasDev173 @MicaCisneros pasenme su usuario/email de postman asi los invito al team del workspace de postman
