### ISSUE TITLE
Tareas TP5: microservicio Customers

### ISSUE THREAD

**Issue by ezequielcinalli** [ezequielcinalli/tpe-arquitecturas-web#13]
- [x] Crear projecto spring (TP5/Customers)
- [x] ABM
- [x] Generar mock data(10 registros aprox)
- [x] Servicio punto 2
- [x] Generar/probar documentacion swagger

**Comment by Germandf** [comment]
@ezequielcinalli @gherbiandrea ya tienen el endpoint sales/amount/{customerId} funcionando. A modo de ejemplo, el cliente 1 tiene una compra con dos productos. En total les devuelve 8000.

Les dejé una línea comentada en LoadDatabase.java del proyecto Sales a modo de guía.

``` java
var saleProduct1 = new SaleProduct(sale1, 1, 2, 1000);
var saleProduct11 = new SaleProduct(sale1, 2, 3, 2000);
// sales/amount/1 should return saleProduct1 + saleProduct11 = 8000
```
