### ISSUE TITLE
Tareas TP5: microservicio Products

### ISSUE THREAD

**Issue by ezequielcinalli** [ezequielcinalli/tpe-arquitecturas-web#15]
- [x] Crear projecto spring (TP5/Products)
- [x] Crud
- [x] Generar mock data(10 registros aprox)
- [x] Generar/probar documentacion swagger

**Comment by Germandf** [comment]
@LucasDev173 @MicaCisneros el endpoint get por id no estaba funcionando, arrojaba error. Ahí lo corregí porque me daba error a mí al implementar el punto 4 ya que necesito consultarlo.

Prueben por favor el resto y verifiquen que los datos se estén registrando/actualizando/eliminando correctamente.
