### ISSUE TITLE
Tareas TP5: Autenticación JWT

### ISSUE THREAD

**Issue by Germandf** [ezequielcinalli/tpe-arquitecturas-web#17]
La idea es crear un controlador `Auth` en cada microservicio con un único endpoint `auth/sign-in`. Como parámetro debe recibir en el body un dto con los siguientes campos:

`SignInDto`
``` json
{
  "user": "example",
  "password": "example"
}
```

El controlador dentro deberá pasar el body a un servicio `AuthService` a un método `SignIn`.

El método `SignIn` debe verificar que el usuario coincida con los datos hardcodeados definidos en el diagrama de drawio:

```
user: "usuariointerno"
password: "usuariointerno"
```

Si coincide, llama a la librería que implemente jwt para crear un token que incluya esos datos (exceptuando la contraseña). Tener en cuenta que esto no es una implementación que funcione en un ambiente real en producción, ya que no contiene ningún id y podemos pasar datos de otro usuario en cualquier endpoint. La idea es que los controladores sólo verifiquen que la firma (signature) del jwt sea válido (que se haya creado usando nuestro `secret`).

![image](https://user-images.githubusercontent.com/69018178/201757369-58d82fbb-dd7e-405c-a7ae-41cb39f33b53.png)

El secret tiene que ser en los 3 microservicios el mismo ya que sino no van a ser válidos. Hay que definir cuál usamos, ejemplo: `7639b3c8-68cb-42fa-80b7-d159a680c7f2` (sacado de https://www.guidgenerator.com/online-guid-generator.aspx, puede ser cualquier cosa). Después vemos si un `salt` también, etc.

Todo esto es para la llamada del usuario desde afuera. Luego, para que los microservicios se comuniquen entre sí internamente, vamos a tener que generar otro jwt desde el servicio que llama a otro microservicio, usando el mismo `secret`. Ni siquiera tiene por qué estar relacionado a un usuario, la idea es que sea un jwt con firma válida para poder hacer la consulta y listo.

Todo esto se puede ver en el diagrama de drawio, la idea es bajarlo a texto para que la interpretación sea por todos la misma.

![image](https://user-images.githubusercontent.com/69018178/201758524-56f4829e-3e9a-4380-b07a-07568031d42f.png)

Por último, aclarar que el controlador y servicio van a ser en los 3 proyectos exactamente el mismo código. Con que uno lo tenga andando bien primero, todos podemos copiar el código de él.

Si algo no está claro vamos editando el comentario. Cerramos una vez esté implementado en los 3 microservicios.

**Comment by ezequielcinalli** [comment]
De la propuesta original de german, inverti la logica de autorizacion para hacer publicos los url de swagger ya que son mas de 1 (el /swagger-ui/index.html llama a otros url internamente), solo autenticando los endpoints del controller necesario y todo lo demas queda publico. `/**` es una expresion regular que indica cualquier cosa despues de la barra.

![image](https://user-images.githubusercontent.com/70036411/201804228-6d35871d-566c-4517-aa66-ef92ebe59890.png)
