### ISSUE TITLE
Entidad Student: model, repository, service y controller

### ISSUE THREAD

**Issue by ezequielcinalli** [ezequielcinalli/tpe-arquitecturas-web#6]
Sub tareas:

- [x] Crear model
- [x] Crear repository
- [x] Crear service
- [x] Crear controller
- [x] Usar Dtos para agregar y actualizar @Germandf 
- [x] Implementar 2a) dar de alta un estudiante @Germandf 
- [x] Implementar 2c) recuperar todos los estudiantes, y especificar algún criterio de ordenamiento simple. @MicaCisneros o @LucasDev173 
- [x] Implementar 2d) recuperar un estudiante, en base a su número de libreta universitaria.
- [x] Implementar 2e) recuperar todos los estudiantes, en base a su género. @MicaCisneros o @LucasDev173 
- [x] Implementar 2g) recuperar los estudiantes de una determinada carrera, filtrado por ciudad de residencia @MicaCisneros o @LucasDev173

**Comment by Germandf** [comment]
@ezequielcinalli hola eze, después decime qué opinas de usar un "AddOrUpdateDto" en vez de un add y un update por separado que queden iguales. Implementé el ejemplo con el caso de estudiante (StudentAddOrUpdateDto)

**Comment by ezequielcinalli** [comment]
> @ezequielcinalli hola eze, después decime qué opinas de usar un "AddOrUpdateDto" en vez de un add y un update por separado que queden iguales. Implementé el ejemplo con el caso de estudiante (StudentAddOrUpdateDto)

Hola ger si tambien me paso con `City` y `StudentCareer` que quedan iguales los dtos add/update. 

Agrego como info extra (capas es obvio pero no para todos) que me parece que la solucion ideal mas extensible/escalable seria tener por ejemplo para City un `CityBaseDto` con los campos comunes y despues que `CityAddDto` y `CityUpdateDto` extiendan de la clase base(quedando clases vacias que solo extienden), queda barbaro pero seguro es overkill para este problema. 

Me gusta la idea de compartir el mismo Dto, capas "AddOrUpdateDto" no me convence tanto (capas estoy muy purista de los principios pero el nombre ya me da indicio que el dto tiene mas de 1 responsabilidad y rompe la S de los SOLID) y le pondria "CityDto" o "CityBaseDto" que te da un poquito mas de juego a la hora de extension, igualmente naming muy fino. Avisame si te convence alguna opcion como para coordinar todos los dtos iguales!

**Comment by Germandf** [comment]
Tal cual. Pensé llamarlo StudentDto directamente pero el problema es que no lleva id, el dto más base/general (por el nombre propuesto) debería llevarlo me parece.

También es cierto que aunque parecen repetidos, lo mejor puede ser hacer la división que hiciste vos, quedándote un dto por endpoint, perdiendo acople al no compartir. Intenté hacer esa unificación para que el proyecto pareciera más simple, al haber menos archivos/clases.

De última lo consultamos con Nelson el jueves a ver qué opina, total este tipo de cambios se hace en un segundo, no importa si cada uno lo trabajamos distinto mientras unifiquemos al final. 😉
