### ISSUE TITLE
Entidad StudentCareer: model, repository, service y controller

### ISSUE THREAD

**Issue by ezequielcinalli** [ezequielcinalli/tpe-arquitecturas-web#8]
Sub tareas:

- [x] Crear model
- [x] Crear repository
- [x] Crear service
- [x] Crear controller
- [x] Usar Dtos para agregar y actualizar
- [x] Implementar 2b) matricular un estudiante en una carrera
- [x] Implementar 2f) recuperar las carreras con estudiantes inscriptos, y ordenar por cantidad de inscriptos.
- [x] Implementar 2h) generar un reporte de las carreras, que para cada carrera incluya información de los
inscriptos y egresados por año. Se deben ordenar las carreras alfabéticamente, y
presentar los años de manera cronológica.
- [x] Corregir id compuesto de StudentCareer al utilizar los endpoints @ezequielcinalli

**Comment by Germandf** [comment]
El reporte de las carreras lo dejamos para el final y lo vemos todos juntos

**Comment by ezequielcinalli** [comment]
Agregadas implementaciones pero faltan testear tanto el crud como los servicios 2b-2f en postman (dependen de las implementaciones de student y career, y de la seed data)

**Comment by ezequielcinalli** [comment]
Tenemos algun bug porque se "glitchea" la api con la seed data. 

![image](https://user-images.githubusercontent.com/70036411/195596464-b1a01f99-b9af-4265-9310-85f2a7267f66.png)
![image](https://user-images.githubusercontent.com/70036411/195596684-c65f1603-b9c7-4f99-8c83-89813cf8c037.png)


Comentando las ultimas 10 lineas de la seed data donde se cargan los `StudentCareer`, los `Student` y `Career` andan bien es medio raro.
![image](https://user-images.githubusercontent.com/70036411/195596984-765d5fbd-8667-4095-a594-140ebc013713.png)

Tendriamos que ver que el controller retorne un `ShowDto` en lugar del entity crudo que tiene referencias a objetos, debe entrar en bucle o quedarse sin memoria la base in-memory o algo asi.
