### ISSUE TITLE
LoadData: completar mock data para todas las entities

### ISSUE THREAD

**Issue by ezequielcinalli** [ezequielcinalli/tpe-arquitecturas-web#9]
[Clase donde se carga la seed data](https://github.com/ezequielcinalli/tpe-arquitecturas-web/blob/main/TP3/src/main/java/com/example/tp3/Utils/LoadDatabase.java)

Sub tareas:

- [x] Seed data para city
- [x] Seed data para student
- [x] Seed data para career
- [x] Seed data para studentCareer
- [x] Solucionar bug glitch en api
- [ ] Solucionar bug en fechas( todas aparecen en 1969-12-31)

**Comment by Germandf** [comment]
@LucasDev173 @MicaCisneros repartanse la carga de datos o decidan quién de los dos la hace.

La idea es tener 10 registros por tabla aprox. ya que en este caso se hacen a mano en la clase LoadData.java y hacer muchos sería medio tedioso.

**Comment by ezequielcinalli** [comment]
Tenemos algun bug porque se "glitchea" la api con la seed data. 

![image](https://user-images.githubusercontent.com/70036411/195596464-b1a01f99-b9af-4265-9310-85f2a7267f66.png)
![image](https://user-images.githubusercontent.com/70036411/195596684-c65f1603-b9c7-4f99-8c83-89813cf8c037.png)


Comentando las ultimas 10 lineas de la seed data donde se cargan los `StudentCareer`, los `Student` y `Career` andan bien es medio raro.
![image](https://user-images.githubusercontent.com/70036411/195596984-765d5fbd-8667-4095-a594-140ebc013713.png)

Tendriamos que ver que el controller retorne un `ShowDto` en lugar del entity crudo que tiene referencias a objetos, debe entrar en bucle o quedarse sin memoria la base in-memory o algo asi.

**Comment by Germandf** [comment]
Solucionado usando el atributo JsonIgnore en las listas a StudentCareer desde Student y Career
